name: Documentation

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: artifacts/PROJECT.ecd
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.TOK }}
